FROM python:3.9

#Install python packages
RUN /usr/local/bin/python -m pip install --upgrade pip \
    && pip install mlflow boto3 psycopg2 \
    && apt-get update -y && apt-get install sqlite3 -y
EXPOSE 5000
ENTRYPOINT ["mlflow", "server"]